# -*- coding: utf-8 -*-
"""Driver_Behavior_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RU6XDhhga2MOxcqDSNaCWeQQfeGBIBDl

Importing Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""Unzipping & Extracting"""

import zipfile
import os

zip_path = '/content/drive/MyDrive/raw_dataset.zip'
extract_path = '/content/driver_dataset'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted to:", extract_path)

for root, dirs, files in os.walk('/content/driver_dataset'):
    level = root.replace('/content/driver_dataset', '').count(os.sep)
    indent = '  ' * level
    print(indent + os.path.basename(root) + '/')

    for file in files[:10]:
        print(indent + '  ' + file)

    if level >= 2:
        dirs[:] = []

import glob
import pandas as pd
import os

# Find acceleration/braking related CSV files
files = glob.glob('/content/driver_dataset/*.csv')

selected_files = [
    f for f in files
    if any(keyword in os.path.basename(f).lower()
           for keyword in [
               'sudden-acc',
               'sudden-brake',
               'safe_acc',
               'safe-acc',
               'safe-no-movement'
           ])
]

print("Number of selected files:", len(selected_files))

for f in selected_files:
    print(os.path.basename(f))

# Load each file and retain its source filename
parts = []

for f in selected_files:
    temp = pd.read_csv(f)
    temp['source_file'] = os.path.basename(f)
    parts.append(temp)

df = pd.concat(parts, ignore_index=True)

print("Combined dataset shape:", df.shape)
print("Unique source files:", df['source_file'].nunique())

"""Cleaning the dataset. The dataset already had no missing values and no duplicate rows."""

print(df.shape)
display(df.head())
print("\nColumns:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("Event class distribution:")
display(df['event_class'].value_counts())

print("\nHarsh event distribution:")
display(df['harsh_event'].value_counts())

display(df[['acc_x', 'acc_y', 'acc_z',
            'gyro_x', 'gyro_y', 'gyro_z',
            'mag_x', 'mag_y', 'mag_z']].describe())

pd.crosstab(df['harsh_event'], df['event_class'])

# Acceleration statistics

acc_cols = ['acc_x', 'acc_y', 'acc_z']

print("=== Acceleration Statistics ===")

acc_stats = df[acc_cols].describe().T

print(acc_stats)

# Calculate total acceleration magnitude

df['acc_magnitude'] = np.sqrt(
    df['acc_x']**2 +
    df['acc_y']**2 +
    df['acc_z']**2
)

df[['acc_x', 'acc_y', 'acc_z', 'acc_magnitude']].describe()

# Acceleration statistics by driving event

event_stats = df.groupby('harsh_event')['acc_magnitude'].agg([
    'count',
    'mean',
    'std',
    'min',
    'max',
    'median'
]).sort_values('mean', ascending=False)

print(event_stats)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))

sns.histplot(df['acc_magnitude'], bins=50, kde=True)

plt.title('Distribution of Acceleration Magnitude')
plt.xlabel('Acceleration Magnitude')
plt.ylabel('Frequency')
plt.show()

"""1. Overall acceleration magnitude distribution

Most acceleration magnitudes are concentrated around 2–7.
The distribution is right-skewed, meaning most driving samples have moderate acceleration while a smaller number have very high acceleration.
Values extend up to around 57, which explains the long tail and the outliers.
"""

plt.figure(figsize=(12, 6))

sns.boxplot(
    data=df,
    x='harsh_event',
    y='acc_magnitude'
)

plt.title('Acceleration Magnitude by Driving Event')
plt.xlabel('Driving Event')
plt.ylabel('Acceleration Magnitude')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""2. Boxplot by driving event

sudden-acc has one of the highest median acceleration magnitudes.
sudden-brake also has a relatively high median.
cons-acc-20 has the lowest median among the events.
There are many high-value outliers, especially for sudden-acc and sudden-brake.
"""

# Calculate IQR

Q1 = df['acc_magnitude'].quantile(0.25)
Q3 = df['acc_magnitude'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

outliers = df[
    (df['acc_magnitude'] < lower_bound) |
    (df['acc_magnitude'] > upper_bound)
]

print("Number of potential outliers:", len(outliers))
print("Percentage of potential outliers:",
      len(outliers) / len(df) * 100)

outlier_event_counts = (
    outliers['harsh_event']
    .value_counts()
)

print(outlier_event_counts)

outlier_event_percentage = (
    outliers['harsh_event']
    .value_counts(normalize=True) * 100
)

print(outlier_event_percentage)

# Count potential high-acceleration outliers

outliers = df[df['acc_magnitude'] > upper_bound]

print("Potential high-acceleration outliers:", len(outliers))
print("Percentage of dataset:",
      round(len(outliers) / len(df) * 100, 2), "%")

# Calculate overall acceleration magnitude
df['acc_magnitude'] = np.sqrt(
    df['acc_x']**2 +
    df['acc_y']**2 +
    df['acc_z']**2
)

df[['acc_x', 'acc_y', 'acc_z', 'acc_magnitude']].head()

plt.figure(figsize=(12, 6))

sns.histplot(
    data=df,
    x='acc_magnitude',
    hue='harsh_event',
    bins=40,
    kde=True,
    element='step',
    common_norm=False
)

plt.title('Acceleration Magnitude Distribution by Driving Event')
plt.xlabel('Acceleration Magnitude')
plt.ylabel('Density')
plt.show()

"""The data suggests that sudden acceleration and sudden braking are associated with stronger acceleration-magnitude changes than controlled acceleration events."""

plt.figure(figsize=(12, 7))

sns.boxplot(
    data=df,
    x='harsh_event',
    y='acc_magnitude'
)

plt.title('Acceleration Magnitude by Driving Event')
plt.xlabel('Driving Event')
plt.ylabel('Acceleration Magnitude')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 7))

sns.boxplot(
    data=df,
    x='harsh_event',
    y='acc_magnitude',
    showfliers=False
)

plt.title('Acceleration Magnitude by Driving Event (Outliers Hidden)')
plt.xlabel('Driving Event')
plt.ylabel('Acceleration Magnitude')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""4. Boxplot with outliers hidden

This is particularly useful because it makes the normal range of each driving event easier to compare without the extreme values dominating the visualization.

Feature Engineering
"""

# Work on the feature-engineered copy
df_features = df.copy()

# Make sure rows are in their original file order
df_features['_row_order'] = df_features.groupby('source_file').cumcount()

# Absolute acceleration components
df_features['acc_x_abs'] = df_features['acc_x'].abs()
df_features['acc_y_abs'] = df_features['acc_y'].abs()
df_features['acc_z_abs'] = df_features['acc_z'].abs()

# Overall acceleration magnitude
df_features['acc_magnitude'] = np.sqrt(
    df_features['acc_x']**2 +
    df_features['acc_y']**2 +
    df_features['acc_z']**2
)

# Horizontal and vertical acceleration
df_features['horizontal_acc'] = np.sqrt(
    df_features['acc_x']**2 +
    df_features['acc_y']**2
)
df_features['vertical_acc'] = df_features['acc_z'].abs()

# Calculate temporal features separately for each CSV/session
group = df_features.groupby('source_file')['acc_magnitude']

df_features['acc_change'] = group.diff()
df_features['acc_change_abs'] = df_features['acc_change'].abs()

df_features['acc_mean_5'] = (
    group.transform(lambda x: x.rolling(5, min_periods=1).mean())
)

df_features['acc_std_5'] = (
    group.transform(lambda x: x.rolling(5, min_periods=1).std())
)

# First observation of each session has no previous value.
# Replace only those generated NaNs with zero.
df_features['acc_change'] = df_features['acc_change'].fillna(0)
df_features['acc_change_abs'] = df_features['acc_change_abs'].fillna(0)
df_features['acc_std_5'] = df_features['acc_std_5'].fillna(0)

# Acceleration intensity
def acceleration_level(x):
    if x < 2:
        return 'Low'
    elif x < 5:
        return 'Moderate'
    elif x < 10:
        return 'High'
    else:
        return 'Extreme'

df_features['acceleration_level'] = (
    df_features['acc_magnitude'].apply(acceleration_level)
)

# Aggressive driving
df_features['aggressive_driving'] = (
    df_features['event_class'] == 1
).astype(int)

# Harsh braking
df_features['is_harsh_braking'] = (
    df_features['harsh_event'] == 'sudden-brake'
).astype(int)

# Rapid acceleration
df_features['is_rapid_acceleration'] = (
    df_features['harsh_event'].isin([
        'sudden-acc',
        'sudden-acceleration'
    ])
).astype(int)

# Smooth acceleration
df_features['is_smooth_acceleration'] = (
    df_features['harsh_event'].isin([
        'uniform-accel',
        'cons-acc-20',
        'cons-acc-40'
    ])
).astype(int)

df_features = df_features.drop(columns=['_row_order'])
print("Feature engineering completed.")

feature_columns = [
    'acc_x',
    'acc_y',
    'acc_z',
    'acc_magnitude',
    'horizontal_acc',
    'vertical_acc',
    'acc_x_abs',
    'acc_y_abs',
    'acc_z_abs',
    'acc_mean_5',
    'acc_std_5',
    'acc_change',
    'acc_change_abs',
    'acceleration_level',
    'aggressive_driving',
    'is_harsh_braking',
    'is_rapid_acceleration',
    'is_smooth_acceleration'
]

df_features[feature_columns].head()

acc_summary = df.groupby('harsh_event')['acc_magnitude'].agg(
    ['count', 'mean', 'std', 'min', 'median', 'max']
).round(3)

acc_summary

# Threshold obtained from the IQR outlier analysis
aggressive_threshold = 10.32959034570605

# Classify driving behavior
df['driving_style'] = np.where(
    df['acc_magnitude'] > aggressive_threshold,
    'Aggressive',
    'Smooth'
)

# Check the result
df[['acc_magnitude', 'driving_style']].head(10)

style_counts = df['driving_style'].value_counts()

print("Driving Style Counts:")
print(style_counts)

print("\nDriving Style Percentages:")
print((style_counts / len(df) * 100).round(2))

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x='driving_style'
)

plt.title('Aggressive vs Smooth Driving')
plt.xlabel('Driving Style')
plt.ylabel('Number of Samples')

plt.show()

style_by_event = pd.crosstab(
    df['harsh_event'],
    df['driving_style']
)

print(style_by_event)

style_by_event_percent = pd.crosstab(
    df['harsh_event'],
    df['driving_style'],
    normalize='index'
) * 100

print(style_by_event_percent.round(2))

plt.figure(figsize=(10,6))

sns.countplot(
    data=df,
    x='harsh_event',
    hue='driving_style'
)

plt.title('Aggressive vs Smooth Driving by Event')
plt.xlabel('Driving Event')
plt.ylabel('Number of Samples')
plt.xticks(rotation=30)

plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))

sns.boxplot(
    data=df,
    x='driving_style',
    y='acc_magnitude'
)

plt.title('Acceleration Magnitude: Aggressive vs Smooth Driving')
plt.xlabel('Driving Style')
plt.ylabel('Acceleration Magnitude')

plt.show()

style_statistics = df.groupby('driving_style')['acc_magnitude'].agg(
    count='count',
    mean='mean',
    std='std',
    min='min',
    median='median',
    max='max'
)

print(style_statistics.round(3))

aggressive_events = (
    df[df['driving_style'] == 'Aggressive']
    .groupby('harsh_event')
    .size()
    .sort_values(ascending=False)
)

print("Aggressive samples by event:")
print(aggressive_events)

aggressive_event_percent = (
    df[df['driving_style'] == 'Aggressive']
    .groupby('harsh_event')
    .size()
    / df.groupby('harsh_event').size()
    * 100
)

print("Percentage of aggressive samples within each event:")
print(aggressive_event_percent.round(2).sort_values(ascending=False))

output_path = '/content/drive/MyDrive/driver_dataset_feature_engineered.csv'

df.to_csv(output_path, index=False)

print("Saved to:", output_path)

"""Model Training"""

feature_columns = [
    'acc_x',
    'acc_y',
    'acc_z',
    'acc_magnitude',
    'horizontal_acc',
    'vertical_acc',
    'acc_x_abs',
    'acc_y_abs',
    'acc_z_abs',
    'acc_mean_5',
    'acc_std_5',
    'acc_change',
    'acc_change_abs'
]

# Input features
X = df_features[feature_columns].copy()

# Target
y = df['event_class'].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

print("\nTarget percentage:")
print((y.value_counts(normalize=True) * 100).round(2))

print("\nMissing values:")
print(X.isnull().sum())

print("\nTotal missing values:", X.isnull().sum().sum())

ml_data = df_features[feature_columns + ['event_class']].dropna().copy()

print("Original dataset:", df.shape)
print("ML dataset after removing missing values:", ml_data.shape)

print("\nMissing values after cleaning:")
print(ml_data[feature_columns].isnull().sum().sum())

X = ml_data[feature_columns]
y = ml_data['event_class']

print("X shape:", X.shape)
print("y shape:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

print("\nTraining class distribution:")
print(y_train.value_counts())

print("\nTesting class distribution:")
print(y_test.value_counts())

"""Random Forest"""

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced',
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print("Random Forest training completed!")

# Predictions and probabilities for the held-out test set

y_test_proba = rf_model.predict_proba(X_test)[:, 1]

FINAL_THRESHOLD = 0.15

y_test_final = (
    y_test_proba >= FINAL_THRESHOLD
).astype(int)

# Keep the default model prediction as well
y_pred = rf_model.predict(X_test)

print("Predictions generated!")
print("First 20 predictions:", y_pred[:20])
print("Final threshold:", FINAL_THRESHOLD)

# ============================================================
# STEP 1 — FIND AND REMOVE DUPLICATE CSV COPIES
# ============================================================

import glob
import os
import hashlib
import pandas as pd

# Find CSVs only in your actual dataset folder
csv_files = glob.glob('/content/driver_dataset/*.csv')

print("CSV files found:", len(csv_files))


# ------------------------------------------------------------
# Check for duplicate files using file content
# ------------------------------------------------------------

file_hashes = {}

for file in csv_files:

    with open(file, 'rb') as f:
        file_hash = hashlib.md5(f.read()).hexdigest()

    file_hashes.setdefault(file_hash, []).append(file)


# ------------------------------------------------------------
# Display duplicate groups
# ------------------------------------------------------------

duplicate_groups = [
    files for files in file_hashes.values()
    if len(files) > 1
]

print("Duplicate groups:", len(duplicate_groups))

for i, group in enumerate(duplicate_groups, 1):

    print(f"\nDuplicate group {i}:")

    for file in group:
        print("  ", os.path.basename(file))


# ------------------------------------------------------------
# Keep only ONE copy of each file
# ------------------------------------------------------------

unique_csv_files = [
    files[0]
    for files in file_hashes.values()
]

print("\n==========================================")
print("FINAL FILE COUNT")
print("==========================================")

print("Original CSV count:", len(csv_files))
print("Unique CSV count:", len(unique_csv_files))
print("Duplicate copies removed:",
      len(csv_files) - len(unique_csv_files))

# ============================================================
# STEP 2 — CHECK UNIQUE DRIVING SESSIONS
# ============================================================

session_info = []

for file in unique_csv_files:

    temp = pd.read_csv(file)

    class_counts = temp['event_class'].value_counts()

    session_info.append({
        'filename': os.path.basename(file),
        'rows': len(temp),
        'class_0': class_counts.get(0, 0),
        'class_1': class_counts.get(1, 0)
    })

sessions_df = pd.DataFrame(session_info)

print(sessions_df.to_string(index=False))

print("\n==========================================")
print("TOTAL UNIQUE ROWS")
print("==========================================")

print("Total rows:", sessions_df['rows'].sum())

# ============================================================
# FINAL FILE-LEVEL UNSEEN-DATA EXPERIMENT
# ============================================================

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

print("Total unique CSV files:", len(unique_csv_files))
print("Total raw rows:", sessions_df['rows'].sum())

# Prefer the final unseen file used in the project.
preferred_unseen_name = (
    'paved_sudden-right-line-chg_const-acc-at-20kmph_22-3-2023_19-37-54.csv'
)

preferred_matches = [
    f for f in unique_csv_files
    if os.path.basename(f) == preferred_unseen_name
]

if preferred_matches:
    UNSEEN_FILE = preferred_matches[0]
else:
    # Fallback: reproducibly select a file containing both classes.
    rng = np.random.RandomState(42)
    candidate_files = []

    for file in unique_csv_files:
        temp = pd.read_csv(file)
        if (
            'event_class' in temp.columns
            and temp['event_class'].nunique() == 2
            and temp['event_class'].value_counts().min() >= 50
        ):
            candidate_files.append(file)

    if not candidate_files:
        raise ValueError("No suitable unseen CSV containing both classes was found.")

    UNSEEN_FILE = rng.choice(candidate_files)

print("\n==========================================")
print("GENUINELY UNSEEN FILE")
print("==========================================")
print(os.path.basename(UNSEEN_FILE))

unseen_original = pd.read_csv(UNSEEN_FILE)

print("Rows:", len(unseen_original))
print("\nClass distribution:")
print(unseen_original['event_class'].value_counts())

feature_columns = [
    'acc_x', 'acc_y', 'acc_z', 'acc_magnitude',
    'horizontal_acc', 'vertical_acc',
    'acc_x_abs', 'acc_y_abs', 'acc_z_abs',
    'acc_mean_5', 'acc_std_5',
    'acc_change', 'acc_change_abs'
]

def create_features(data):
    data = data.copy()

    data['acc_magnitude'] = np.sqrt(
        data['acc_x']**2 + data['acc_y']**2 + data['acc_z']**2
    )
    data['horizontal_acc'] = np.sqrt(
        data['acc_x']**2 + data['acc_y']**2
    )
    data['vertical_acc'] = data['acc_z'].abs()

    data['acc_x_abs'] = data['acc_x'].abs()
    data['acc_y_abs'] = data['acc_y'].abs()
    data['acc_z_abs'] = data['acc_z'].abs()

    data['acc_mean_5'] = (
        data['acc_magnitude'].rolling(5, min_periods=1).mean()
    )
    data['acc_std_5'] = (
        data['acc_magnitude'].rolling(5, min_periods=1).std()
    )

    data['acc_change'] = data['acc_magnitude'].diff()
    data['acc_change_abs'] = data['acc_change'].abs()

    # Match the main feature-engineering treatment of first-row/session NaNs.
    data['acc_change'] = data['acc_change'].fillna(0)
    data['acc_change_abs'] = data['acc_change_abs'].fillna(0)
    data['acc_std_5'] = data['acc_std_5'].fillna(0)

    return data

train_files = [f for f in unique_csv_files if f != UNSEEN_FILE]

train_parts = []
for file in train_files:
    temp = create_features(pd.read_csv(file))
    temp = temp[feature_columns + ['event_class']].dropna(
        subset=feature_columns + ['event_class']
    )
    train_parts.append(temp)

train_df_final = pd.concat(train_parts, ignore_index=True)

unseen_df_final = create_features(unseen_original)
unseen_df_final = unseen_df_final[
    feature_columns + ['event_class']
].dropna(subset=feature_columns + ['event_class'])

X_train_final = train_df_final[feature_columns]
y_train_final = train_df_final['event_class']
X_unseen_final = unseen_df_final[feature_columns]
y_unseen_final = unseen_df_final['event_class']

print("\n==========================================")
print("FINAL DATASET SIZES")
print("==========================================")
print("Training:", X_train_final.shape)
print("Unseen:", X_unseen_final.shape)
print("\nTraining class distribution:")
print(y_train_final.value_counts())
print("\nUnseen class distribution:")
print(y_unseen_final.value_counts())

final_rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1,
    class_weight='balanced'
)

final_rf.fit(X_train_final, y_train_final)

print("\nRandom Forest training completed.")

unseen_probabilities = final_rf.predict_proba(X_unseen_final)[:, 1]

# Use the same project operating threshold.
THRESHOLD = FINAL_THRESHOLD

unseen_predictions = (
    unseen_probabilities >= THRESHOLD
).astype(int)

accuracy = accuracy_score(y_unseen_final, unseen_predictions)
precision = precision_score(y_unseen_final, unseen_predictions, zero_division=0)
recall = recall_score(y_unseen_final, unseen_predictions, zero_division=0)
f1 = f1_score(y_unseen_final, unseen_predictions, zero_division=0)
roc_auc = roc_auc_score(y_unseen_final, unseen_probabilities)

print("\n==========================================")
print("FINAL UNSEEN-DATA PERFORMANCE")
print("==========================================")
print("Unseen file:", os.path.basename(UNSEEN_FILE))
print("Threshold:", THRESHOLD)
print(f"\nAccuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")
print(f"ROC-AUC   : {roc_auc:.4f}")

print("\nClassification Report:")
print(classification_report(
    y_unseen_final,
    unseen_predictions,
    target_names=['Non-Aggressive', 'Aggressive'],
    zero_division=0
))

cm = confusion_matrix(y_unseen_final, unseen_predictions)
print("\nConfusion Matrix:")
print(cm)

plt.figure(figsize=(7, 5))
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=['Non-Aggressive (0)', 'Aggressive (1)'],
    yticklabels=['Non-Aggressive (0)', 'Aggressive (1)']
)
plt.title('Final Random Forest - Unseen Driving Session')
plt.xlabel('Predicted Class')
plt.ylabel('Actual Class')
plt.tight_layout()
plt.show()

# Compatibility aliases used by later cells.
# unseen_df keeps the complete unseen feature dataframe for representative predictions.
unseen_df = create_features(unseen_original)

# ============================================================
# FINAL MODEL — FEATURE IMPORTANCE ANALYSIS
# ============================================================

feature_importance = pd.DataFrame({
    'Feature': feature_columns,
    'Importance': rf_model.feature_importances_
}).sort_values(
    'Importance',
    ascending=False
).reset_index(drop=True)

print("==========================================")
print("FINAL FEATURE IMPORTANCE")
print("==========================================")
print(feature_importance)

plt.figure(figsize=(10, 7))
sns.barplot(
    data=feature_importance,
    x='Importance',
    y='Feature'
)
plt.title('Random Forest Feature Importance')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

# ============================================================
# ERROR ANALYSIS VISUALIZATION
# ============================================================

error_analysis = X_test.copy()
error_analysis['actual'] = y_test.values
error_analysis['predicted'] = y_test_final

def prediction_type(row):
    if row['actual'] == 1 and row['predicted'] == 1:
        return 'True Positive'
    if row['actual'] == 0 and row['predicted'] == 1:
        return 'False Positive'
    if row['actual'] == 0 and row['predicted'] == 0:
        return 'True Negative'
    return 'False Negative'

error_analysis['prediction_type'] = error_analysis.apply(
    prediction_type,
    axis=1
)

plt.figure(figsize=(8, 5))
sns.countplot(
    data=error_analysis,
    x='prediction_type',
    order=[
        'True Negative',
        'False Positive',
        'False Negative',
        'True Positive'
    ]
)
plt.title('Final Model Prediction Analysis')
plt.xlabel('Prediction Type')
plt.ylabel('Number of Samples')
plt.xticks(rotation=20)
plt.tight_layout()
plt.show()

print("Error summary:")
print(
    error_analysis['prediction_type']
    .value_counts()
    .reindex([
        'True Positive',
        'False Positive',
        'True Negative',
        'False Negative'
    ])
)

# ==========================================
# FINAL MODEL EVALUATION SETUP
# ==========================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    precision_recall_curve,
    average_precision_score
)

# Final operating threshold
FINAL_THRESHOLD = 0.15

y_final_pred = (y_test_proba >= FINAL_THRESHOLD).astype(int)

final_accuracy = accuracy_score(y_test, y_final_pred)
final_precision = precision_score(y_test, y_final_pred, zero_division=0)
final_recall = recall_score(y_test, y_final_pred, zero_division=0)
final_f1 = f1_score(y_test, y_final_pred, zero_division=0)
final_roc_auc = roc_auc_score(y_test, y_test_proba)
final_pr_auc = average_precision_score(y_test, y_test_proba)

print("=" * 60)
print("FINAL RANDOM FOREST EVALUATION")
print("=" * 60)

print(f"Threshold : {FINAL_THRESHOLD:.2f}")
print(f"Accuracy  : {final_accuracy:.4f}")
print(f"Precision : {final_precision:.4f}")
print(f"Recall    : {final_recall:.4f}")
print(f"F1 Score  : {final_f1:.4f}")
print(f"ROC-AUC   : {final_roc_auc:.4f}")
print(f"PR-AUC    : {final_pr_auc:.4f}")

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_final_pred,
    target_names=['Non-Aggressive', 'Aggressive'],
    digits=4
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_final_pred))

# ==========================================
# FINAL PERFORMANCE METRICS
# ==========================================

final_accuracy = accuracy_score(y_test, y_test_final)
final_precision = precision_score(y_test, y_test_final, zero_division=0)
final_recall = recall_score(y_test, y_test_final, zero_division=0)
final_f1 = f1_score(y_test, y_test_final, zero_division=0)
final_roc_auc = roc_auc_score(y_test, y_test_proba)
final_pr_auc = average_precision_score(y_test, y_test_proba)

print("=" * 50)
print("FINAL RANDOM FOREST PERFORMANCE")
print("=" * 50)

print(f"Threshold : {FINAL_THRESHOLD:.2f}")
print(f"Accuracy  : {final_accuracy:.4f}")
print(f"Precision : {final_precision:.4f}")
print(f"Recall    : {final_recall:.4f}")
print(f"F1 Score  : {final_f1:.4f}")
print(f"ROC-AUC   : {final_roc_auc:.4f}")
print(f"PR-AUC    : {final_pr_auc:.4f}")

cm = confusion_matrix(y_test, y_final_pred)

plt.figure(figsize=(7, 6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['Non-Aggressive (0)', 'Aggressive (1)'],
    yticklabels=['Non-Aggressive (0)', 'Aggressive (1)']
)

plt.title('Final Random Forest Confusion Matrix (Threshold = 0.15)')
plt.xlabel('Predicted Class')
plt.ylabel('Actual Class')

plt.tight_layout()
plt.show()

# ==========================================
# ROC CURVE
# ==========================================

fpr, tpr, roc_thresholds = roc_curve(y_test, y_test_proba)

plt.figure(figsize=(8, 6))

plt.plot(
    fpr,
    tpr,
    linewidth=2,
    label=f'Random Forest (AUC = {final_roc_auc:.3f})'
)

plt.plot(
    [0, 1],
    [0, 1],
    linestyle='--',
    label='Random Classifier'
)

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - Random Forest')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# ==========================================
# PRECISION-RECALL CURVE
# ==========================================

precision_curve, recall_curve, pr_thresholds = precision_recall_curve(
    y_test,
    y_test_proba
)

pr_auc = average_precision_score(y_test, y_test_proba)

plt.figure(figsize=(8, 6))

plt.plot(
    recall_curve,
    precision_curve,
    linewidth=2,
    label=f'Random Forest (AP = {pr_auc:.3f})'
)

plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve - Random Forest')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# ==========================================
# SELECTED THRESHOLD ON PR CURVE
# ==========================================

selected_precision = precision_score(
    y_test,
    y_test_final,
    zero_division=0
)

selected_recall = recall_score(
    y_test,
    y_test_final,
    zero_division=0
)

plt.figure(figsize=(8, 6))

plt.plot(
    recall_curve,
    precision_curve,
    linewidth=2,
    label='Precision-Recall Curve'
)

plt.scatter(
    selected_recall,
    selected_precision,
    s=120,
    label=f'Threshold = {FINAL_THRESHOLD}'
)

plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve with Selected Threshold')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

print(f"Selected threshold : {FINAL_THRESHOLD}")
print(f"Precision          : {selected_precision:.4f}")
print(f"Recall             : {selected_recall:.4f}")

# ==========================================
# THRESHOLD ANALYSIS
# ==========================================

thresholds = np.arange(0.10, 0.56, 0.05)

threshold_results = []

for threshold in thresholds:

    predictions = (y_test_proba >= threshold).astype(int)

    precision = precision_score(
        y_test,
        predictions,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        predictions,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        predictions,
        zero_division=0
    )

    accuracy = accuracy_score(
        y_test,
        predictions
    )

    threshold_results.append({
        'Threshold': threshold,
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1': f1
    })

threshold_df = pd.DataFrame(threshold_results)

display(threshold_df.round(4))

# ==========================================
# THRESHOLD PERFORMANCE PLOT
# ==========================================

plt.figure(figsize=(9, 6))

plt.plot(
    threshold_df['Threshold'],
    threshold_df['Precision'],
    marker='o',
    label='Precision'
)

plt.plot(
    threshold_df['Threshold'],
    threshold_df['Recall'],
    marker='o',
    label='Recall'
)

plt.plot(
    threshold_df['Threshold'],
    threshold_df['F1'],
    marker='o',
    label='F1 Score'
)

plt.axvline(
    FINAL_THRESHOLD,
    linestyle='--',
    label=f'Final Threshold = {FINAL_THRESHOLD}'
)

plt.xlabel('Classification Threshold')
plt.ylabel('Score')
plt.title('Model Performance Across Classification Thresholds')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# ==========================================
# FINAL CLASSIFICATION REPORT
# ==========================================

print("=" * 60)
print("FINAL CLASSIFICATION REPORT")
print("=" * 60)

print(
    classification_report(
        y_test,
        y_test_final,
        target_names=[
            'Non-Aggressive',
            'Aggressive'
        ],
        digits=4
    )
)

# ==========================================
# FINAL FEATURE IMPORTANCE
# ==========================================

feature_importance = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': rf_model.feature_importances_
})

feature_importance = (
    feature_importance
    .sort_values('Importance', ascending=False)
    .reset_index(drop=True)
)

display(feature_importance.round(4))

# ==========================================
# FEATURE IMPORTANCE PLOT
# ==========================================

plt.figure(figsize=(10, 7))

plt.barh(
    feature_importance['Feature'],
    feature_importance['Importance']
)

plt.xlabel('Importance')
plt.ylabel('Feature')
plt.title('Random Forest Feature Importance')

plt.gca().invert_yaxis()

plt.tight_layout()
plt.show()

# ==========================================
# FINAL EVALUATION SUMMARY
# ==========================================

final_summary = pd.DataFrame({
    'Metric': [
        'Classification Threshold',
        'Accuracy',
        'Precision',
        'Recall',
        'F1 Score',
        'ROC-AUC',
        'PR-AUC',
        'Test Samples'
    ],
    'Value': [
        FINAL_THRESHOLD,
        final_accuracy,
        final_precision,
        final_recall,
        final_f1,
        final_roc_auc,
        final_pr_auc,
        len(y_test)
    ]
})

display(final_summary.round(4))

# ==========================================
# DRIVER SAFETY SCORE - SETUP
# ==========================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Use the feature-engineered dataset already created above.
# This avoids depending on a separate file named
# 'cleaned_acceleration_braking_dataset.csv'.
df = df_features.copy()

print("Dataset shape:", df.shape)
print("\nUnique source files:", df['source_file'].nunique())
print("\nRequired columns available:")
print([
    c for c in [
        'source_file', 'event_class', 'acc_magnitude',
        'harsh_event'
    ] if c in df.columns
])

# ==========================================
# CREATE / VERIFY REQUIRED FEATURES
# ==========================================

# Acceleration magnitude
if 'acc_magnitude' not in df.columns:
    df['acc_magnitude'] = np.sqrt(
        df['acc_x']**2 +
        df['acc_y']**2 +
        df['acc_z']**2
    )

# Absolute acceleration components
df['acc_x_abs'] = df['acc_x'].abs()
df['acc_y_abs'] = df['acc_y'].abs()
df['acc_z_abs'] = df['acc_z'].abs()

# Horizontal and vertical acceleration
df['horizontal_acc'] = np.sqrt(
    df['acc_x']**2 +
    df['acc_y']**2
)

df['vertical_acc'] = df['acc_z'].abs()

# Rolling acceleration statistics
df['acc_mean_5'] = (
    df.groupby('source_file')['acc_magnitude']
      .transform(lambda x: x.rolling(5, min_periods=1).mean())
)

df['acc_std_5'] = (
    df.groupby('source_file')['acc_magnitude']
      .transform(lambda x: x.rolling(5, min_periods=1).std())
)

# Acceleration change
df['acc_change'] = (
    df.groupby('source_file')['acc_magnitude']
      .diff()
)

df['acc_change_abs'] = df['acc_change'].abs()

# Fill the first-row NaN generated by diff()
df['acc_change'] = df['acc_change'].fillna(0)
df['acc_change_abs'] = df['acc_change_abs'].fillna(0)
df['acc_std_5'] = df['acc_std_5'].fillna(0)

print("Required features created.")

# ==========================================
# BEHAVIOURAL INDICATORS
# ==========================================

# Aggressive event indicator
df['aggressive_event'] = (df['event_class'] == 1).astype(int)

# ------------------------------------------
# Harsh braking
# ------------------------------------------

# Existing feature?
if 'is_harsh_braking' not in df.columns:

    braking_events = [
        'sudden-brake'
    ]

    df['is_harsh_braking'] = (
        df['harsh_event']
        .isin(braking_events)
        .astype(int)
    )


# ------------------------------------------
# Rapid acceleration
# ------------------------------------------

if 'is_rapid_acceleration' not in df.columns:

    acceleration_events = [
        'sudden-acc',
        'sudden-acceleration'
    ]

    df['is_rapid_acceleration'] = (
        df['harsh_event']
        .isin(acceleration_events)
        .astype(int)
    )


# ------------------------------------------
# Smooth acceleration
# ------------------------------------------

if 'is_smooth_acceleration' not in df.columns:

    # Smooth acceleration = relatively low
    # short-term acceleration variation
    smooth_threshold = df['acc_std_5'].quantile(0.50)

    df['is_smooth_acceleration'] = (
        (df['acc_std_5'] <= smooth_threshold) &
        (df['is_rapid_acceleration'] == 0) &
        (df['is_harsh_braking'] == 0)
    ).astype(int)


print("\nIndicator counts:")
print("Aggressive events :", df['aggressive_event'].sum())
print("Harsh braking     :", df['is_harsh_braking'].sum())
print("Rapid acceleration:", df['is_rapid_acceleration'].sum())
print("Smooth acceleration:", df['is_smooth_acceleration'].sum())

# ==========================================
# RANDOM FOREST PREDICTIONS
# ==========================================

FINAL_THRESHOLD = 0.15

feature_columns = [
    'acc_x', 'acc_y', 'acc_z',
    'acc_magnitude', 'horizontal_acc', 'vertical_acc',
    'acc_x_abs', 'acc_y_abs', 'acc_z_abs',
    'acc_mean_5', 'acc_std_5',
    'acc_change', 'acc_change_abs'
]

missing_features = [c for c in feature_columns if c not in df.columns]

if missing_features:
    raise ValueError(f"Missing features: {missing_features}")

ml_df = df.dropna(subset=feature_columns).copy()

ml_df['aggressive_probability'] = (
    rf_model.predict_proba(ml_df[feature_columns])[:, 1]
)

ml_df['model_aggressive'] = (
    ml_df['aggressive_probability'] >= FINAL_THRESHOLD
).astype(int)

print("Predictions generated.")
print("Rows used:", len(ml_df))

# ==========================================
# TRIP-LEVEL BEHAVIOURAL INDICATORS
# ==========================================

trip_summary = (
    ml_df
    .groupby('source_file')
    .agg(
        total_samples=('event_class', 'size'),

        # Ground-truth aggressive rate
        aggressive_event_rate=('aggressive_event', 'mean'),

        # Model-predicted aggressive rate
        predicted_aggressive_rate=('model_aggressive', 'mean'),

        # Average model confidence
        mean_aggressive_probability=(
            'aggressive_probability',
            'mean'
        ),

        # Harsh braking
        harsh_braking_rate=(
            'is_harsh_braking',
            'mean'
        ),

        # Rapid acceleration
        rapid_acceleration_rate=(
            'is_rapid_acceleration',
            'mean'
        ),

        # Smooth driving
        smooth_acceleration_rate=(
            'is_smooth_acceleration',
            'mean'
        ),

        # Acceleration behaviour
        mean_acceleration=(
            'acc_magnitude',
            'mean'
        ),

        median_acceleration=(
            'acc_magnitude',
            'median'
        ),

        acceleration_variability=(
            'acc_std_5',
            'mean'
        ),

        mean_acc_change=(
            'acc_change_abs',
            'mean'
        )
    )
    .reset_index()
)

print("Trip-level dataset:")
display(trip_summary.head())

print("\nNumber of trips:", len(trip_summary))

# ==========================================
# CONVERT RATES TO PERCENTAGES
# ==========================================

rate_columns = [
    'aggressive_event_rate',
    'predicted_aggressive_rate',
    'harsh_braking_rate',
    'rapid_acceleration_rate',
    'smooth_acceleration_rate'
]

for col in rate_columns:
    trip_summary[col + '_pct'] = (
        trip_summary[col] * 100
    )

display(
    trip_summary[
        [
            'source_file',
            'total_samples',
            'aggressive_event_rate_pct',
            'predicted_aggressive_rate_pct',
            'harsh_braking_rate_pct',
            'rapid_acceleration_rate_pct',
            'smooth_acceleration_rate_pct'
        ]
    ].head(10).round(2)
)

# ==========================================
# NORMALIZE RISK INDICATORS
# ==========================================

def percentile_risk(series):
    """
    Converts a value into a 0-100 percentile risk.
    Higher value = higher risk.
    """
    return series.rank(pct=True) * 100


trip_summary['aggressive_risk'] = percentile_risk(
    trip_summary['predicted_aggressive_rate']
)

trip_summary['braking_risk'] = percentile_risk(
    trip_summary['harsh_braking_rate']
)

trip_summary['rapid_accel_risk'] = percentile_risk(
    trip_summary['rapid_acceleration_rate']
)

trip_summary['variability_risk'] = percentile_risk(
    trip_summary['acceleration_variability']
)

trip_summary['acc_change_risk'] = percentile_risk(
    trip_summary['mean_acc_change']
)

# Smoothness works in the opposite direction:
# more smooth driving = lower risk
trip_summary['smoothness_risk'] = (
    100 -
    percentile_risk(
        trip_summary['smooth_acceleration_rate']
    )
)

display(
    trip_summary[
        [
            'source_file',
            'aggressive_risk',
            'braking_risk',
            'rapid_accel_risk',
            'variability_risk',
            'acc_change_risk',
            'smoothness_risk'
        ]
    ].head().round(2)
)

# ==========================================
# DRIVER SAFETY SCORE
# ==========================================

WEIGHTS = {
    'aggressive_risk': 0.30,
    'braking_risk': 0.20,
    'rapid_accel_risk': 0.20,
    'variability_risk': 0.15,
    'acc_change_risk': 0.10,
    'smoothness_risk': 0.05
}

trip_summary['risk_score'] = (
    trip_summary['aggressive_risk'] *
    WEIGHTS['aggressive_risk']

    + trip_summary['braking_risk'] *
    WEIGHTS['braking_risk']

    + trip_summary['rapid_accel_risk'] *
    WEIGHTS['rapid_accel_risk']

    + trip_summary['variability_risk'] *
    WEIGHTS['variability_risk']

    + trip_summary['acc_change_risk'] *
    WEIGHTS['acc_change_risk']

    + trip_summary['smoothness_risk'] *
    WEIGHTS['smoothness_risk']
)

# Convert risk into safety score
trip_summary['safety_score'] = (
    100 - trip_summary['risk_score']
)

# Keep score between 0 and 100
trip_summary['safety_score'] = (
    trip_summary['safety_score']
    .clip(0, 100)
)

print("Safety scores calculated.")

# ==========================================
# SAFETY SCORE CATEGORIES
# ==========================================

def safety_category(score):

    if score >= 80:
        return 'Safe'

    elif score >= 60:
        return 'Moderate'

    elif score >= 40:
        return 'Risky'

    else:
        return 'High Risk'


trip_summary['risk_level'] = (
    trip_summary['safety_score']
    .apply(safety_category)
)

display(
    trip_summary[
        [
            'source_file',
            'safety_score',
            'risk_level'
        ]
    ]
    .sort_values(
        'safety_score',
        ascending=False
    )
    .round(2)
)

# ==========================================
# FINAL SAFETY SCORE TABLE
# ==========================================

final_safety_table = trip_summary[
    [
        'source_file',
        'total_samples',

        'aggressive_event_rate_pct',
        'predicted_aggressive_rate_pct',

        'harsh_braking_rate_pct',
        'rapid_acceleration_rate_pct',
        'smooth_acceleration_rate_pct',

        'mean_acceleration',
        'acceleration_variability',
        'mean_acc_change',

        'safety_score',
        'risk_level'
    ]
].copy()

final_safety_table = final_safety_table.sort_values(
    'safety_score',
    ascending=True
)

display(
    final_safety_table.round(2)
)

# ==========================================
# SAFETY SCORE DISTRIBUTION
# ==========================================

plt.figure(figsize=(10, 6))

sns.histplot(
    trip_summary['safety_score'],
    bins=10,
    kde=True
)

plt.axvline(80, linestyle='--', label='Safe boundary')
plt.axvline(60, linestyle='--', label='Moderate boundary')
plt.axvline(40, linestyle='--', label='Risky boundary')

plt.xlabel('Safety Score')
plt.ylabel('Number of Trips')
plt.title('Driver Safety Score Distribution')
plt.legend()

plt.tight_layout()
plt.show()

# ==========================================
# RISK LEVEL DISTRIBUTION
# ==========================================

risk_counts = (
    trip_summary['risk_level']
    .value_counts()
    .reindex(
        ['Safe', 'Moderate', 'Risky', 'High Risk'],
        fill_value=0
    )
)

plt.figure(figsize=(8, 5))

sns.barplot(
    x=risk_counts.index,
    y=risk_counts.values
)

plt.xlabel('Risk Level')
plt.ylabel('Number of Trips')
plt.title('Driver Risk-Level Distribution')

plt.tight_layout()
plt.show()

print(risk_counts)

# ==========================================
# EXPORT FINAL SAFETY SCORE DATASET
# ==========================================

output_file = "final_driver_safety_scores.csv"

final_safety_table.to_csv(
    output_file,
    index=False
)

print(f"Saved: {output_file}")

from google.colab import files

files.download("final_driver_safety_scores.csv")

# ==========================================
# REPRESENTATIVE FINAL PREDICTIONS
# ==========================================

unseen_results = unseen_df.copy()

# Remove rows with incomplete model features.
unseen_results = unseen_results.dropna(
    subset=feature_columns
).copy()

X_unseen = unseen_results[feature_columns]

unseen_results['aggressive_probability'] = (
    rf_model.predict_proba(X_unseen)[:, 1]
)

FINAL_THRESHOLD = 0.15

unseen_results['predicted_class'] = (
    unseen_results['aggressive_probability'] >= FINAL_THRESHOLD
).astype(int)

unseen_results['prediction'] = unseen_results['predicted_class'].map({
    0: 'Non-Aggressive',
    1: 'Aggressive'
})

representative_predictions = unseen_results[
    [
        'aggressive_probability',
        'prediction',
        'acc_magnitude',
        'horizontal_acc',
        'vertical_acc',
        'acc_mean_5',
        'acc_std_5',
        'acc_change_abs'
    ]
].sort_values(
    'aggressive_probability',
    ascending=False
)

print("TOP AGGRESSIVE PREDICTIONS")
display(representative_predictions.head(5).round(3))

print("\nTOP NON-AGGRESSIVE PREDICTIONS")
display(
    representative_predictions
    .sort_values('aggressive_probability')
    .head(5)
    .round(3)
)

# ==========================================
# FINAL PREDICTION SUMMARY
# ==========================================

prediction_summary = pd.DataFrame({
    'Metric': [
        'Total unseen samples',
        'Predicted Non-Aggressive',
        'Predicted Aggressive',
        'Predicted Aggressive %',
        'Mean Aggressive Probability'
    ],
    'Value': [
        len(unseen_results),
        (unseen_results['predicted_class'] == 0).sum(),
        (unseen_results['predicted_class'] == 1).sum(),
        (unseen_results['predicted_class'] == 1).mean() * 100,
        unseen_results['aggressive_probability'].mean()
    ]
})

display(prediction_summary.round(3))